/**
 * Fuentes canónicas por dominio (verificadas en investigación 2026-09).
 * Usado por `ctx7max add --pack <dominio>` y por scripts/seed-domains.mts.
 * Cada entrada es una fuente soportada por el pipeline: github/llmstxt/website/wiki/etc.
 */
export const DOMAIN_SOURCES: Record<string, string[]> = {
  "web-backend": [
    "https://github.com/honojs/hono",
    "https://github.com/fastify/fastify",
    "https://github.com/expressjs/express",
    "https://github.com/trpc/trpc",
  ],
  android: [
    "https://github.com/android/nowinandroid",
    "https://github.com/android/compose-samples",
    "https://github.com/android/architecture-samples",
    "https://github.com/android/tv-samples",
    "https://github.com/android/wear-os-samples",
    "https://github.com/android/user-interface-samples",
    "https://github.com/googlecodelabs/android-compose-codelabs",
  ],
  "ios-macos": [
    "https://github.com/swiftlang/swift-book",
    "https://github.com/swiftlang/swift-evolution",
    "https://github.com/pointfreeco/swift-composable-architecture",
    "https://developer.apple.com/documentation/swiftui",
    "https://developer.apple.com/documentation/appkit",
  ],
  "mobile-multiplatform": [
    "https://github.com/flutter/website",
    "https://github.com/react/react-native-website",
    "https://github.com/expo/expo",
    "https://github.com/JetBrains/kotlin-web-site",
    "https://github.com/dotnet/docs-maui",
  ],
  desktop: [
    "https://github.com/MicrosoftDocs/windows-dev-docs",
    "https://github.com/MicrosoftDocs/win32",
    "https://github.com/microsoft/microsoft-ui-xaml",
    "https://github.com/electron/electron",
    "https://github.com/tauri-apps/tauri-docs",
    "https://github.com/flatpak/flatpak-docs",
  ],
  gamedev: [
    "https://github.com/godotengine/godot-docs",
    "https://github.com/KhronosGroup/Vulkan-Docs",
    "https://github.com/JoeyDeVries/LearnOpenGL",
    "https://github.com/patriciogonzalezvivo/thebookofshaders",
    "https://github.com/munificent/game-programming-patterns",
    "https://dev.epicgames.com/llms.txt",
  ],
  "consoles-homebrew": [
    "https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain",
    "https://github.com/switchbrew/libnx",
    "https://github.com/devkitPro/installer",
    "https://switchbrew.org/wiki",
    "https://www.psdevwiki.com",
  ],
  tv: [
    "https://github.com/Samsung/tizen-docs",
    "https://webostv.developer.lge.com",
    "https://developer.samsung.com/smarttv/develop/overview.html",
    "https://developer.android.com/training/tv",
  ],
  wearables: [
    "https://developer.android.com/wear",
    "https://github.com/google/horologist",
    "https://developer.apple.com/documentation/watchkit",
  ],
  osdev: [
    "https://github.com/phil-opp/blog_os",
    "https://github.com/cfenollosa/os-tutorial",
    "https://github.com/0xAX/linux-insides",
    "https://github.com/sysprog21/lkmpg",
    "https://github.com/mit-pdos/xv6-riscv",
    "https://github.com/SerenityOS/serenity",
    "https://wiki.osdev.org",
  ],
  "kernel-drivers": [
    "https://github.com/torvalds/linux.git#Documentation",
    "https://github.com/bootlin/training-materials",
    "https://www.kernel.org/doc/html/latest/",
  ],
  embedded: [
    "https://github.com/raspberrypi/documentation",
    "https://github.com/raspberrypi/pico-sdk",
    "https://github.com/zephyrproject-rtos/zephyr",
    "https://github.com/embassy-rs/embassy",
    "https://github.com/espressif/esp-idf",
    "https://github.com/riscv/riscv-isa-manual",
    "https://github.com/FreeRTOS/FreeRTOS",
  ],
  "linux-distros": [
    "https://github.com/CachyOS/wiki",
    "https://github.com/CachyOS/linux-cachyos",
    "https://wiki.archlinux.org",
    "https://wiki.gentoo.org",
    "https://www.linuxfromscratch.org",
  ],
  "ai-courses": [
    // cursos/libros abiertos canónicos por laboratorios (verificados sep-2026)
    "https://github.com/microsoft/ai-agents-for-beginners",
    "https://github.com/microsoft/generative-ai-for-beginners",
    "https://github.com/microsoft/ML-For-Beginners",
    "https://github.com/huggingface/agents-course",
    "https://github.com/huggingface/smol-course",
    "https://github.com/anthropics/courses",
    "https://github.com/anthropics/claude-cookbooks",
    "https://github.com/anthropics/prompt-eng-interactive-tutorial",
    "https://github.com/openai/openai-cookbook",
    "https://github.com/dair-ai/Prompt-Engineering-Guide",
    "https://github.com/mlabonne/llm-course",
    "https://github.com/langchain-ai/langchain-academy",
    "https://github.com/mistralai/cookbook",
    "https://github.com/HandsOnLLM/Hands-On-Large-Language-Models",
    "https://github.com/fastai/fastbook",
    "https://github.com/labmlai/annotated_deep_learning_paper_implementations",
    "https://github.com/rdi-berkeley/agentic-ai",
    "https://github.com/somosnlp/nlp-de-cero-a-cien",
    "https://github.com/SWE-agent/minimal-agent-tutorial",
    "https://github.com/disler/claude-code-hooks-mastery",
    "https://github.com/xai-org/grok-prompts",
  ],
  "agents-frameworks": [
    // frameworks y herramientas de agentes (creadores verificados sep-2026)
    "https://github.com/Significant-Gravitas/AutoGPT",
    "https://github.com/OpenHands/OpenHands",
    "https://github.com/kortix-ai/suna",
    "https://github.com/simular-ai/Agent-S",
    "https://github.com/FoundationAgents/MetaGPT",
    "https://github.com/huggingface/smolagents",
    "https://github.com/browser-use/browser-use",
    "https://github.com/SWE-agent/SWE-agent",
    "https://github.com/SWE-agent/mini-swe-agent",
    "https://github.com/openinterpreter/openinterpreter",
    "https://github.com/Aider-AI/aider",
    "https://github.com/microsoft/autogen",
    "https://github.com/pydantic/pydantic-ai",
    "https://github.com/googleapis/genai-toolbox",
    "https://github.com/ggml-org/llama.cpp",
    "https://github.com/joonspk-research/generative_agents",
    "https://github.com/yoheinakajima/babyagi",
    "https://github.com/openai/evals",
  ],
  "system-one": [
    // Jev (TypeSafe, propietario) y equivalentes open-source (sep-2026)
    "https://docs.typesafe.ai/llms.txt",
    "https://github.com/typesafe-ai/typesafe-sdk-js",
    "https://github.com/typesafe-ai/typesafe-sdk-python",
    "https://github.com/typesafe-ai/system-one-adapter-python",
    "https://github.com/typesafe-ai/skills",
    "https://github.com/NandhaKishorM/laya",
    "https://github.com/TheoLeeCJ/SemIf",
    "https://github.com/kotoba-lang/typed-decisions",
    "https://github.com/ikermoel/open-alternative-jev",
    "https://github.com/tacticocc/Jevbridge",
    "https://github.com/razorback16/openjev",
    "https://github.com/featherless-ai/simple-jev",
    // ecosistema Jev open-source (verificado via X/Charlie Hills)
    "https://github.com/browser-use/jev-ultrafast",
    "https://github.com/tamaratran/fast-jev-compaction",
    "https://github.com/vercel-labs/json-render",
    "https://github.com/itsmostafa/typesafe-mcp",
    "https://github.com/jkudish/jev-mcp",
    "https://github.com/sharziki/semdecide",
    "https://github.com/0xNatoshi/jev-codex-router",
    "https://github.com/GhalebDweikat/winnow",
    "https://github.com/devagrawal09/jev-review",
    "https://github.com/ellipsis-dev/blink",
    "https://github.com/lahfir/agent-desktop",
    "https://github.com/fhshaik/typesafe-mario",
    "https://github.com/RomanSlack/jev-drone",
    "https://github.com/emrickgarrett/OneVOneJev",
    "https://github.com/jarrodwatts/jev-trader",
    "https://github.com/irfndi/prism-liquidity-agent",
    "https://github.com/jexp/neo4jev",
    "https://github.com/AkashPriyadarshii/jev-curate",
    "https://github.com/qkal/Canny",
    "https://github.com/monteduro/killmyidea",
  ],
  creators: [
    // guías/libros/currículos de agentes-IA creados por creadores
    "https://github.com/coleam00/context-engineering-intro",
    "https://github.com/ThePrimeagen/99",
    "https://github.com/karpathy/nn-zero-to-hero",
    "https://github.com/rasbt/LLMs-from-scratch",
    "https://github.com/chiphuyen/aie-book",
    "https://github.com/simonw/llm",
    "https://github.com/jxnl/instructor",
    "https://github.com/simonw/showboat",
    "https://github.com/midudev/github-sentinel",
    "https://github.com/midudev/strands-midu-demo",
    "https://github.com/CodelyTV/mcp_servers-course",
    "https://github.com/CodelyTV/rpi-course",
    "https://github.com/CodelyTV/agentic_programming-course",
    "https://github.com/CodelyTV/agent-harness",
    "https://github.com/CodelyTV/typescript-mcp-client",
    "https://github.com/HackTricks-wiki/hacktricks",
    "https://github.com/bradtraversy/skillpass",
    "https://github.com/ringa-tech/tu-primer-agente-de-ia",
    "https://github.com/hwchase17/agent-patterns",
  ],
  cybersecurity: [
    "https://github.com/OWASP/CheatSheetSeries",
    "https://github.com/OWASP/Top10",
    "https://github.com/OWASP/wstg",
    "https://github.com/OWASP/ASVS",
    "https://github.com/OWASP/mastg",
    "https://github.com/HackTricks-wiki/hacktricks",
    "https://github.com/swisskyrepo/PayloadsAllTheThings",
    "https://github.com/trimstray/the-book-of-secret-knowledge",
    "https://github.com/sbilly/awesome-security",
    "https://github.com/redcanaryco/atomic-red-team",
    "https://github.com/SigmaHQ/sigma",
    "https://github.com/trailofbits/ctf",
    "https://github.com/osirislab/ctf101",
    "https://github.com/guyinatuxedo/nightmare",
    "https://github.com/mitre-attack/attack-stix-data",
  ],
};

export type DomainPack = keyof typeof DOMAIN_SOURCES;
